/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-04-2014
 * 
 * XDoclet definition:
 * @struts.form name="MminfoForm"
 */
public class MinfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** topic property */
	private String topic;

	/** startTime property */
	private String startTime;

	/** userId property */
	private String userId;

	/** meetingId property */
	private String meetingId;

	/** endTime property */
	private String endTime;

	/** date property */
	private String date;

	/** meetingroomId property */
	private String meetingroomId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the topic.
	 * @return String
	 */
	public String getTopic() {
		return topic;
	}

	/** 
	 * Set the topic.
	 * @param topic The topic to set
	 */
	public void setTopic(String topic) {
		this.topic = topic;
	}

	/** 
	 * Returns the startTime.
	 * @return String
	 */
	public String getStartTime() {
		return startTime;
	}

	/** 
	 * Set the startTime.
	 * @param startTime The startTime to set
	 */
	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	/** 
	 * Returns the userId.
	 * @return String
	 */
	public String getUserId() {
		return userId;
	}

	/** 
	 * Set the userId.
	 * @param userId The userId to set
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/** 
	 * Returns the meetingId.
	 * @return String
	 */
	public String getMeetingId() {
		return meetingId;
	}

	/** 
	 * Set the meetingId.
	 * @param meetingId The meetingId to set
	 */
	public void setMeetingId(String meetingId) {
		this.meetingId = meetingId;
	}

	/** 
	 * Returns the endTime.
	 * @return String
	 */
	public String getEndTime() {
		return endTime;
	}

	/** 
	 * Set the endTime.
	 * @param endTime The endTime to set
	 */
	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	/** 
	 * Returns the date.
	 * @return String
	 */
	public String getDate() {
		return date;
	}

	/** 
	 * Set the date.
	 * @param date The date to set
	 */
	public void setDate(String date) {
		this.date = date;
	}

	/** 
	 * Returns the meetingroomId.
	 * @return String
	 */
	public String getMeetingroomId() {
		return meetingroomId;
	}

	/** 
	 * Set the meetingroomId.
	 * @param meetingroomId The meetingroomId to set
	 */
	public void setMeetingroomId(String meetingroomId) {
		this.meetingroomId = meetingroomId;
	}
}